# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: employee-postgres-data-storage
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: test
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: employee-postgres-data-storage
          persistentVolumeClaim:
            claimName: employee-postgres-data-persisent-volume-claim