# web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: employee-web-service
spec:
  type: NodePort
  selector:
    app: employee-web
  ports:
    - name: "http"
      protocol: TCP
      port: 5000
      targetPort: 9000
      nodePort: 31140
  type: LoadBalancer
  
